import { defineField, defineType } from "sanity";

export default defineType({
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Product Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      description: "Generated from the Product Name. You can edit it if needed.",
      options: { source: "name", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "price",
      title: "Price (₹)",
      type: "number",
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: "fabricRef",
      title: "Fabric",
      type: "reference",
      to: [{ type: "fabric" }],
      description: "Choose from the Fabric list. Use Custom Fabric below for a one-off value.",
    }),
    defineField({
      name: "customFabric",
      title: "Custom Fabric",
      type: "string",
      description: "Optional. If filled, this is shown instead of the selected Fabric.",
    }),
    defineField({
      name: "fabric",
      title: "Legacy Fabric",
      type: "string",
      hidden: true,
    }),
    defineField({
      name: "description",
      title: "Full Description",
      type: "text",
      rows: 5,
    }),
    defineField({
      name: "sizeRefs",
      title: "Sizes",
      type: "array",
      of: [{ type: "reference", to: [{ type: "size" }], options: { filter: "active == true" } }],
      description: "Add every size this product is available in (e.g. S, M, L, XL). Click 'Add item' for each one.",
    }),
    defineField({
      name: "customSizes",
      title: "Custom Sizes",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "Optional extra sizes not in the Size list above (e.g. 'Free Size', 'XXL').",
    }),
    defineField({
      name: "sizeRef",
      title: "Legacy Size",
      type: "reference",
      to: [{ type: "size" }],
      hidden: true,
    }),
    defineField({
      name: "sizes",
      title: "Legacy Size Names",
      type: "array",
      of: [{ type: "string" }],
      hidden: true,
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: { list: ["In Stock", "Made to Order", "Sold Out"], layout: "radio" },
      initialValue: "In Stock",
    }),
    defineField({
      name: "badge",
      title: "Badge",
      type: "string",
      options: { list: ["New", "Bestseller"] },
      description: "Also shows up automatically in Website Banner & Settings for quick management.",
    }),
    defineField({
      name: "images",
      title: "Product Photos",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      options: { layout: "grid" },
      description: "Add multiple photos. The first photo is the primary product image.",
      validation: (Rule) => Rule.min(1),
    }),
    defineField({
      name: "image",
      title: "Legacy Main Image",
      type: "image",
      options: { hotspot: true },
      hidden: true,
    }),
  ],
  preview: {
    select: { title: "name", subtitle: "customFabric", media: "images.0" },
  },
});
